M48
; DRILL file KiCad 10.0.5 date 2026-09-18T10:15:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-18T10:15:00+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X102.3Y-133.01
X102.3Y-139.81
T2
X102.75Y-24.75
X102.75Y-167.5
X200.25Y-167.75
X200.5Y-25.25
M30
